<a href="https://colab.research.google.com/github/makbd71/Pyhton_learning/blob/main/NumPy_Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

##you can pick any number based on postion. *** But remmeber Python starts from "0"

array1 = np.array([10,20,30,40,50])

fourth = array1 [4]

print(fourth)

50


In [8]:
### Using (-), you can came from the back door

print(array1[-1])

50


In [10]:
### Here we tried to find the number between 1-4 but *** try to remmember your number came between 1-4

sliced = array1[1:4]
print(sliced)

[20 30 40]


In [12]:
### by using this formula you will get every number after 3 number

step_array = array1[: :3]
print(step_array)

[10 40]


In [16]:
# Here us a **2d** array, using '[]' are very carefully

matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

ele = matrix [1,1]
print(ele)

5


In [19]:
## get the informaiton of whole 2nd row

second_row = matrix [1,:]
print(second_row)

[4 5 6]


In [21]:
## get the informaiton of whole 2nd Column

second_col = matrix [:,0]
print(second_col)

[1 4 7]


In [23]:
### using this fuction yiu can findout the missing information. **when you try to find out in your data sher were is the missing data


data = np.array ([1,2,3,np.nan,5,6,7])

missing = np.isnan(data)

print(missing)

[False False False  True False False False]


In [25]:
### Now you find the nul vaule and you want to replace

data_fill = np.nan_to_num (data, nan=100)
print(data_fill)

[  1.   2.   3. 100.   5.   6.   7.]
